Vagrant.configure("2") do |config|
    config.vm.define "maquina2" do |debian|
    debian.vm.box = "debian/buster64"
    debian.vm.network "forwarded_port", guest: 80, host: 8888, host_ip: "127.0.0.1"
    debian.vm.network "public_network", bridge: "Realtek Gaming GbE Family Controller", ip: "192.168.1.22"
    debian.vm.provision "shell", inline: "sudo apt update -y && sudo apt dist-upgrade -y"
    debian.vm.provision "shell", inline: "sudo apt install python3"
    debian.vm.provision "shell", inline: "sudo apt install python-is-python3 -y"
    debian.vm.provision "shell", inline: "sudo apt install python3-pip -y"
    debian.vm.provision "shell", inline: "sudo python -m pip install --upgrade pip"
    debian.vm.provider "virtualbox" do |vb|
        vb.name = "maquina2"
        vb.gui = true
        vb.memory = "1024"
        vb.cpus = "2"
    end
  end
end