Vagrant.configure("2") do |config|
  config.vm.define "master" do |ubuntu|
  ubuntu.vm.box = "ubuntu/focal64"
  ubuntu.vm.network "forwarded_port", guest: 80, host: 8000, host_ip: "127.0.0.1"
  ubuntu.vm.network "public_network", bridge: "Realtek Gaming GbE Family Controller", ip: "192.168.1.20"
  #ubuntu.vm.provision "shell", inline: "sudo apt update -y && sudo apt dist-upgrade -y"
  ubuntu.vm.provision "shell", inline: "sudo apt install python3"
  ubuntu.vm.provision "shell", inline: "sudo apt install python-is-python3 -y"
  ubuntu.vm.provision "shell", inline: "sudo apt install python3-pip -y"
  ubuntu.vm.provision "shell", inline: "sudo python -m pip install --upgrade pip"
  ubuntu.vm.provision "shell", inline: "sudo pip install ansible==2.9.10"
  
  ubuntu.vm.provider "virtualbox" do |vb|
    vb.name = "master"
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = "2"
  end
 end
end